import themes from './colors'

export default function getTheme() {
  const theme = {
    name: 'E-Ink',
    base: 'hc-light',
    $schema: 'vscode://schemas/color-theme',
    colors: {
      // Contrast colors
      contrastActiveBorder: themes.border,
      contrastBorder: themes.border,

      // Base colors
      focusBorder: themes.border,
      foreground: themes.foreground,
      'widget.border': themes.border,
      'widget.shadow': themes.shadow,
      'selection.background': themes.primaryBackground,
      descriptionForeground: themes.foreground,
      // errorForeground: themes.error,
      'icon.foreground': themes.primary,
      'sash.hoverBorder': themes.primary,

      // Window border
      'window.activeBorder': themes.border,
      'window.inactiveBorder': themes.border,

      // Text colors
      'textBlockQuote.background': themes.background,
      'textBlockQuote.border': themes.border,
      'textCodeBlock.background': themes.background,
      'textLink.foreground': themes.secondary,
      'textLink.activeForeground': themes.foreground,
      'textPreformat.foreground': themes.primary,
      'textSeparator.foreground': themes.primary,

      // Action colors
      'toolbar.hoverBackground': themes.background,
      'toolbar.hoverOutline': themes.primary,
      'toolbar.activeBackground': themes.primary,

      // Button control
      'button.background': themes.background,
      'button.foreground': themes.foreground,
      'button.border': themes.border,
      'button.separator': themes.primary,
      'button.hoverBackground': themes.primaryBackground,
      // 'button.secondaryForeground': themes.primary,
      // 'button.secondaryBackground': themes.background,
      // 'button.secondaryHoverBackground': themes.primary,
      'checkbox.background': themes.background,
      'checkbox.foreground': themes.foreground,
      'checkbox.border': themes.border,
      'checkbox.selectBackground': themes.primary,
      'checkbox.selectBorder': themes.border,

      // Dropdown control
      'dropdown.background': themes.background,
      'dropdown.border': themes.border,
      'dropdown.foreground': themes.foreground,
      'dropdown.listBackground': themes.background,

      // Input control
      'input.background': themes.background,
      'input.border': themes.border,
      'input.foreground': themes.foreground,
      'input.placeholderForeground': themes.secondary,
      'inputOption.activeBackground': themes.background,
      'inputOption.activeBorder': themes.border,
      'inputOption.activeForeground': themes.primary,
      'inputOption.hoverBackground': themes.background,
      // 'inputValidation.errorBackground': themes.background,
      // 'inputValidation.errorForeground': themes.warn,
      // 'inputValidation.errorBorder': themes.border,
      // 'inputValidation.infoBackground': themes.background,
      // 'inputValidation.infoForeground': themes.foreground,
      // 'inputValidation.infoBorder': themes.border,
      // 'inputValidation.warningBackground': themes.background,
      // 'inputValidation.warningForeground': themes.foreground,
      // 'inputValidation.warningBorder': themes.border,

      // Scrollbar control
      'scrollbar.shadow': themes.shadow,
      'scrollbarSlider.activeBackground': themes.secondary,
      'scrollbarSlider.background': themes.primaryBackground,
      'scrollbarSlider.hoverBackground': themes.secondary,

      // Badge
      'badge.foreground': themes.foreground,
      'badge.background': themes.background,

      // Progress bar
      'progressBar.background': themes.primary,

      // Lists and trees
      'list.activeSelectionBackground': themes.background,
      'list.activeSelectionForeground': themes.foreground,
      'list.activeSelectionIconForeground': themes.foreground,
      'list.dropBackground': themes.primaryBackground,
      'list.focusBackground': themes.background,
      'list.focusForeground': themes.foreground,
      'list.focusHighlightForeground': themes.foreground,
      'list.focusOutline': themes.primary,
      'list.focusAndSelectionOutline': themes.primary,
      'list.highlightForeground': themes.foreground,
      'list.hoverBackground': themes.primaryBackground,
      'list.hoverForeground': themes.foreground,
      'list.inactiveSelectionBackground': themes.background,
      'list.inactiveSelectionForeground': themes.foreground,
      'list.inactiveSelectionIconForeground': themes.foreground,
      'list.inactiveFocusBackground': themes.background,
      'list.inactiveFocusOutline': themes.primary,
      'list.invalidItemForeground': themes.foreground,
      // 'list.errorForeground': themes.error,
      // 'list.warningForeground': themes.warn,
      'listFilterWidget.background': themes.background,
      'listFilterWidget.outline': themes.primary,
      'listFilterWidget.noMatchesOutline': themes.primary,
      'listFilterWidget.shadow': themes.shadow,
      'list.filterMatchBackground': themes.primaryBackground,
      'list.filterMatchBorder': themes.border,
      'list.deemphasizedForeground': themes.foreground,
      'tree.indentGuidesStroke': themes.primary,
      'tree.inactiveIndentGuidesStroke': themes.primary,
      'tree.tableColumnsBorder': themes.border,
      'tree.tableOddRowsBackground': themes.background,

      // Activity Bar
      'activityBar.background': themes.background,
      'activityBar.dropBorder': themes.border,
      'activityBar.foreground': themes.foreground,
      'activityBar.inactiveForeground': themes.foreground,
      'activityBar.border': themes.border,
      'activityBarBadge.background': themes.background,
      'activityBarBadge.foreground': themes.foreground,
      'activityBar.activeBorder': themes.border,
      'activityBar.activeBackground': themes.background,
      'activityBar.activeFocusBorder': themes.border,

      // Profiles
      'profileBadge.background': themes.background,
      'profileBadge.foreground': themes.foreground,

      // Side Bar
      'sideBar.background': themes.background,
      'sideBar.foreground': themes.foreground,
      'sideBar.border': themes.border,
      'sideBar.dropBackground': themes.primaryBackground,
      'sideBarTitle.foreground': themes.foreground,
      'sideBarSectionHeader.background': themes.background,
      'sideBarSectionHeader.foreground': themes.foreground,
      'sideBarSectionHeader.border': themes.border,

      // Minimap
      // 'minimap.findMatchHighlight': '',
      // 'minimap.selectionHighlight': '',
      // 'minimap.errorHighlight': '',
      // 'minimap.warningHighlight': '',
      // 'minimap.background': '',
      // 'minimap.selectionOccurrenceHighlight': '',
      // 'minimap.foregroundOpacity': '',
      // 'minimap.infoHighlight': '',
      // 'minimapSlider.background': '',
      // 'minimapSlider.hoverBackground': '',
      // 'minimapSlider.activeBackground': '',
      // 'minimapGutter.addedBackground': '',
      // 'minimapGutter.modifiedBackground': '',
      // 'minimapGutter.deletedBackground': '',

      // Editor Groups & Tabs
      'editorGroup.border': themes.border,
      'editorGroup.dropBackground': themes.primaryBackground,
      'editorGroupHeader.noTabsBackground': themes.background,
      'editorGroupHeader.tabsBackground': themes.background,
      'editorGroupHeader.tabsBorder': themes.border,
      'editorGroupHeader.border': themes.border,
      'editorGroup.emptyBackground': themes.background,
      'editorGroup.focusedEmptyBorder': themes.border,
      'editorGroup.dropIntoPromptForeground': themes.foreground,
      'editorGroup.dropIntoPromptBackground': themes.background,
      'editorGroup.dropIntoPromptBorder': themes.border,
      'tab.activeBackground': themes.background,
      'tab.unfocusedActiveBackground': themes.background,
      'tab.activeForeground': themes.foreground,
      'tab.border': themes.border,
      'tab.activeBorder': themes.border,
      'tab.unfocusedActiveBorder': themes.border,
      'tab.activeBorderTop': themes.border,
      'tab.unfocusedActiveBorderTop': themes.border,
      'tab.lastPinnedBorder': themes.border,
      'tab.inactiveBackground': themes.background,
      'tab.unfocusedInactiveBackground': themes.background,
      'tab.inactiveForeground': themes.foreground,
      'tab.unfocusedActiveForeground': themes.foreground,
      'tab.unfocusedInactiveForeground': themes.foreground,
      'tab.hoverBackground': themes.background,
      'tab.unfocusedHoverBackground': themes.background,
      'tab.hoverForeground': themes.foreground,
      'tab.unfocusedHoverForeground': themes.foreground,
      'tab.hoverBorder': themes.border,
      'tab.unfocusedHoverBorder': themes.border,
      'tab.activeModifiedBorder': themes.border,
      'tab.inactiveModifiedBorder': themes.border,
      'tab.unfocusedActiveModifiedBorder': themes.border,
      'tab.unfocusedInactiveModifiedBorder': themes.border,
      'editorPane.background': themes.background,
      'sideBySideEditor.horizontalBorder': themes.border,
      'sideBySideEditor.verticalBorder': themes.border,

      // Editor colors
      'editor.background': themes.background,
      'editor.foreground': themes.foreground,
      'editorLineNumber.foreground': themes.foreground,
      'editorLineNumber.activeForeground': themes.secondary,
      'editorLineNumber.dimmedForeground': themes.foreground,
      'editorCursor.background': themes.background,
      'editorCursor.foreground': themes.foreground,
      'editor.selectionBackground': themes.primaryBackground,
      'editor.selectionForeground': themes.background,
      'editor.inactiveSelectionBackground': themes.primaryBackground,
      // 'editor.selectionHighlightBackground': themes.background,
      // 'editor.selectionHighlightBorder': themes.border,
      // 'editor.wordHighlightBackground': themes.background,
      // 'editor.wordHighlightBorder': themes.border,
      // 'editor.wordHighlightStrongBackground': themes.background,
      // 'editor.wordHighlightStrongBorder': themes.border,
      // 'editor.wordHighlightTextBackground': themes.background,
      // 'editor.wordHighlightTextBorder': themes.border,
      'editor.findMatchBackground': themes.primaryBackground,
      // 'editor.findMatchHighlightBackground': themes.background,
      'editor.findRangeHighlightBackground': themes.background,
      'editor.findMatchBorder': themes.border,
      // 'editor.findMatchHighlightBorder': colors.white,
      'editor.findRangeHighlightBorder': themes.border,
      'search.resultsInfoForeground': themes.foreground,
      // 'searchEditor.findMatchBackground':themes.foreground,
      // 'searchEditor.findMatchBorder':themes.foreground,
      // 'searchEditor.textInputBorder':themes.foreground,
      // 'editor.hoverHighlightBackground':themes.background,
      // 'editor.lineHighlightBackground':themes.primary,
      'editor.lineHighlightBorder': themes.border,
      // 'editorUnicodeHighlight.border':themes.primary,
      // 'editorUnicodeHighlight.background':themes.primary,
      'editorLink.activeForeground': themes.secondary,
      // 'editor.rangeHighlightBackground':themes.primary,
      // 'editor.rangeHighlightBorder':themes.primary,
      'editor.symbolHighlightBackground': themes.primaryBackground,
      'editor.symbolHighlightBorder': themes.border,
      'editorWhitespace.foreground': themes.background,
      // 'editorIndentGuide.background': colors.lightpink,
      // 'editorIndentGuide.background1': themes.primary,
      // 'editorIndentGuide.background2': themes.secondary,
      // 'editorIndentGuide.background3': colors.green,
      // 'editorIndentGuide.background4': colors.red,
      // 'editorIndentGuide.background5': colors.orange,
      // 'editorIndentGuide.background6': colors.blue,
      // 'editorIndentGuide.activeBackground': colors.lightpink,
      // 'editorIndentGuide.activeBackground1': themes.primary,
      // 'editorIndentGuide.activeBackground2': themes.secondary,
      // 'editorIndentGuide.activeBackground3': colors.green,
      // 'editorIndentGuide.activeBackground4': colors.red,
      // 'editorIndentGuide.activeBackground5': colors.orange,
      // 'editorIndentGuide.activeBackground6': colors.blue,
      // 'editorInlayHint.background': themes.background,
      // 'editorInlayHint.foreground': themes.foreground,
      // 'editorInlayHint.typeForeground': themes.primary,
      // 'editorInlayHint.typeBackground': themes.primary,
      // 'editorInlayHint.parameterForeground': themes.primary,
      // 'editorInlayHint.parameterBackground': themes.primary,
      'editorRuler.foreground': themes.foreground,
      'editor.linkedEditingBackground': themes.primary,
      'editorCodeLens.foreground': themes.foreground,
      'editorLightBulb.foreground': themes.foreground,
      'editorLightBulbAutoFix.foreground': themes.foreground,
      // 'editorBracketMatch.background':themes.primary,
      // 'editorBracketMatch.border':themes.primary,
      // 'editorBracketHighlight.foreground1': themes.primary,
      // 'editorBracketHighlight.foreground2': themes.primary,
      // 'editorBracketHighlight.foreground3': themes.primary,
      // 'editorBracketHighlight.foreground4': themes.primary,
      // 'editorBracketHighlight.foreground5': themes.primary,
      // 'editorBracketHighlight.foreground6': themes.primary,
      // 'editorBracketHighlight.unexpectedBracket.foreground': themes.secondary,
      // 'editorBracketPairGuide.activeBackground1':themes.primary,
      // 'editorBracketPairGuide.activeBackground2':themes.primary,
      // 'editorBracketPairGuide.activeBackground3':themes.primary,
      // 'editorBracketPairGuide.activeBackground4':themes.primary,
      // 'editorBracketPairGuide.activeBackground5':themes.primary,
      // 'editorBracketPairGuide.activeBackground6':themes.primary,
      // 'editorBracketPairGuide.background1':themes.primary,
      // 'editorBracketPairGuide.background2':themes.primary,
      // 'editorBracketPairGuide.background3':themes.primary,
      // 'editorBracketPairGuide.background4':themes.primary,
      // 'editorBracketPairGuide.background5':themes.primary,
      // 'editorBracketPairGuide.background6':themes.primary,
      // 'editor.foldBackground':themes.primary,
      'editorOverviewRuler.background': themes.background,
      'editorOverviewRuler.border': themes.border,
      'editorOverviewRuler.findMatchForeground': themes.foreground,
      // 'editorOverviewRuler.rangeHighlightForeground':themes.primary,
      // 'editorOverviewRuler.selectionHighlightForeground':themes.primary,
      // 'editorOverviewRuler.wordHighlightForeground':themes.primary,
      // 'editorOverviewRuler.wordHighlightStrongForeground':themes.primary,
      // 'editorOverviewRuler.wordHighlightTextForeground':themes.primary,
      // 'editorOverviewRuler.modifiedForeground':themes.primary,
      // 'editorOverviewRuler.addedForeground':themes.primary,
      // 'editorOverviewRuler.deletedForeground':themes.primary,
      // 'editorOverviewRuler.errorForeground':themes.primary,
      // 'editorOverviewRuler.warningForeground':themes.primary,
      // 'editorOverviewRuler.infoForeground':themes.primary,
      // 'editorOverviewRuler.bracketMatchForeground':themes.primary,
      // 'editorError.foreground':themes.error,
      // 'editorError.border':themes.error,
      // 'editorError.background':colors.white,
      // 'editorWarning.foreground':themes.primary,
      // 'editorWarning.border':themes.primary,
      // 'editorWarning.background':themes.primary,
      // 'editorInfo.foreground':themes.primary,
      // 'editorInfo.border':themes.primary,
      // 'editorInfo.background':themes.primary,
      // 'editorHint.foreground':themes.primary,
      // 'editorHint.border':themes.border,
      // 'problemsErrorIcon.foreground':themes.secondary,
      // 'problemsWarningIcon.foreground':themes.primary,
      // 'problemsInfoIcon.foreground':themes.primary,
      // 'editorUnnecessaryCode.border': themes.primary,
      // 'editorUnnecessaryCode.opacity': themes.primary,
      'editorGutter.background': themes.background,
      'editorGutter.modifiedBackground': themes.primary,
      // 'editorGutter.addedBackground':themes.primary,
      // 'editorGutter.deletedBackground':themes.primary,
      // 'editorGutter.commentRangeForeground':themes.secondary,
      // 'editorGutter.commentGlyphForeground':themes.primary,
      // 'editorGutter.commentUnresolvedGlyphForeground':themes.primary,
      // 'editorGutter.foldingControlForeground':themes.primary,
      // 'editorCommentsWidget.resolvedBorder':themes.primary,
      // 'editorCommentsWidget.unresolvedBorder':themes.primary,
      // 'editorCommentsWidget.rangeBackground':themes.primary,
      // 'editorCommentsWidget.rangeActiveBackground':themes.primary,

      // Diff editor colors
      // 'diffEditor.insertedTextBackground':themes.primaryBackground,
      'diffEditor.insertedTextBorder': themes.border,
      // 'diffEditor.removedTextBackground':themes.primaryBackground,
      'diffEditor.removedTextBorder': themes.border,
      'diffEditor.border': themes.border,
      // 'diffEditor.diagonalFill': themes.secondary,
      // 'diffEditor.insertedLineBackground':themes.primary,
      // 'diffEditor.removedLineBackground':themes.primary,
      // 'diffEditorGutter.insertedLineBackground':themes.primary,
      // 'diffEditorGutter.removedLineBackground':themes.primary,
      // 'diffEditorOverview.insertedForeground':themes.primary,
      // 'diffEditorOverview.removedForeground':themes.primary,
      'diffEditor.unchangedRegionBackground': themes.background,
      'diffEditor.unchangedRegionForeground': themes.secondary,
      'diffEditor.unchangedCodeBackground': themes.background,
      // 'diffEditor.move.border':themes.secondary,
      // 'diffEditor.moveActive.border':themes.primary,

      // Chat colors
      // 'chat.requestBorder': themes.primary,
      // 'chat.slashCommandBackground': themes.primary,
      // 'chat.slashCommandForeground': themes.primary,

      // Inline Chat colors
      // 'inlineChat.background':themes.primary,
      // 'inlineChat.border':themes.primary,
      // 'inlineChat.shadow':themes.primary,
      // 'inlineChat.regionHighlight':themes.primary,
      // 'inlineChatInput.border':themes.primary,
      // 'inlineChatInput.focusBorder':themes.primary,
      // 'inlineChatInput.placeholderForeground':themes.primary,
      // 'inlineChatInput.background':themes.primary,
      // 'inlineChatDiff.inserted':themes.primary,
      // 'inlineChatDiff.removed':themes.primary,

      // Editor widget colors
      // 'editorWidget.foreground': themes.foreground,
      // 'editorWidget.background': themes.background,
      // 'editorWidget.border': themes.border,
      // 'editorWidget.resizeBorder': themes.border,
      // 'editorSuggestWidget.background': themes.primary,
      // 'editorSuggestWidget.border': themes.primary,
      // 'editorSuggestWidget.foreground': themes.primary,
      // 'editorSuggestWidget.focusHighlightForeground': themes.primary,
      // 'editorSuggestWidget.highlightForeground': themes.primary,
      // 'editorSuggestWidget.selectedBackground': themes.primary,
      // 'editorSuggestWidget.selectedForeground': themes.primary,
      // 'editorSuggestWidget.selectedIconForeground': themes.primary,
      // 'editorSuggestWidgetStatus.foreground': themes.primary,
      // 'editorHoverWidget.foreground': themes.foreground,
      // 'editorHoverWidget.background': themes.background,
      // 'editorHoverWidget.border': themes.border,
      // 'editorHoverWidget.highlightForeground': themes.primary,
      // 'editorHoverWidget.statusBarBackground': themes.primary,
      // 'editorGhostText.border': themes.primary,
      // 'editorGhostText.background': themes.primary,
      // 'editorGhostText.foreground': themes.primary,
      // 'editorStickyScroll.background': themes.primary,
      // 'editorStickyScrollHover.background': themes.primary,
      // 'debugExceptionWidget.background': themes.primary,
      // 'debugExceptionWidget.border': themes.primary,
      // 'editorMarkerNavigation.background':themes.primary,
      // 'editorMarkerNavigationError.background':themes.primary,
      // 'editorMarkerNavigationWarning.background':themes.primary,
      // 'editorMarkerNavigationInfo.background':themes.primary,
      // 'editorMarkerNavigationError.headerBackground':themes.primary,
      // 'editorMarkerNavigationWarning.headerBackground':themes.primary,
      // 'editorMarkerNavigationInfo.headerBackground':themes.primary,

      // Peek view colors
      // 'peekView.border': themes.primary,
      // 'peekViewEditor.background': themes.primary,
      // 'peekViewEditorGutter.background': themes.primary,
      // 'peekViewEditor.matchHighlightBackground': themes.primary,
      // 'peekViewEditor.matchHighlightBorder': themes.primary,
      // 'peekViewResult.background': themes.primary,
      // 'peekViewResult.fileForeground': themes.primary,
      // 'peekViewResult.lineForeground': themes.primary,
      // 'peekViewResult.matchHighlightBackground': themes.primary,
      // 'peekViewResult.selectionBackground': themes.primary,
      // 'peekViewResult.selectionForeground': themes.primary,
      // 'peekViewTitle.background': themes.primary,
      // 'peekViewTitleDescription.foreground': themes.primary,
      // 'peekViewTitleLabel.foreground': themes.primary,
      // 'peekViewEditorStickyScroll.background': themes.primary,

      // Merge conflicts colors
      // 'merge.currentHeaderBackground': themes.primary,
      // 'merge.currentContentBackground': themes.primary,
      // 'merge.incomingHeaderBackground': themes.primary,
      // 'merge.incomingContentBackground': themes.primary,
      // 'merge.border': themes.primary,
      // 'merge.commonContentBackground': themes.primary,
      // 'merge.commonHeaderBackground': themes.primary,
      // 'editorOverviewRuler.currentContentForeground': themes.primary,
      // 'editorOverviewRuler.incomingContentForeground': themes.primary,
      // 'editorOverviewRuler.commonContentForeground': themes.primary,
      // 'editorOverviewRuler.commentForeground': themes.primary,
      // 'editorOverviewRuler.commentUnresolvedForeground': themes.primary,
      // 'mergeEditor.change.background': themes.primary,
      // 'mergeEditor.change.word.background': themes.primary,
      // 'mergeEditor.conflict.unhandledUnfocused.border': themes.primary,
      // 'mergeEditor.conflict.unhandledFocused.border': themes.primary,
      // 'mergeEditor.conflict.handledUnfocused.border': themes.primary,
      // 'mergeEditor.conflict.handledFocused.border': themes.primary,
      // 'mergeEditor.conflict.handled.minimapOverViewRuler': themes.primary,
      // 'mergeEditor.conflict.unhandled.minimapOverViewRuler': themes.primary,
      // 'mergeEditor.conflictingLines.background': themes.primary,
      // 'mergeEditor.changeBase.background': themes.primary,
      // 'mergeEditor.changeBase.word.background': themes.primary,
      // 'mergeEditor.conflict.input1.background': themes.primary,
      // 'mergeEditor.conflict.input2.background': themes.primary,

      // Panel colors
      'panel.background': themes.background,
      'panel.border': themes.border,
      'panel.dropBorder': themes.primaryBackground,
      'panelTitle.activeBorder': themes.border,
      'panelTitle.activeForeground': themes.foreground,
      'panelTitle.inactiveForeground': themes.foreground,
      'panelInput.border': themes.border,
      // 'panelSection.border': themes.error,
      // 'panelSection.dropBackground': themes.background,
      // 'panelSectionHeader.background': themes.primary,
      // 'panelSectionHeader.foreground': themes.primary,
      // 'panelSectionHeader.border': themes.primary,

      // Status Bar colors
      'statusBar.background': themes.background,
      'statusBar.foreground': themes.foreground,
      'statusBar.border': themes.border,
      'statusBar.debuggingBackground': themes.background,
      'statusBar.debuggingForeground': themes.primary,
      'statusBar.debuggingBorder': themes.border,
      'statusBar.noFolderForeground': themes.foreground,
      'statusBar.noFolderBackground': themes.background,
      'statusBar.noFolderBorder': themes.border,
      // 'statusBarItem.activeBackground': themes.primary,
      // 'statusBarItem.hoverForeground': themes.foreground,
      // 'statusBarItem.hoverBackground': themes.primary,
      // 'statusBarItem.prominentForeground': themes.error,
      // 'statusBarItem.prominentBackground': themes.primary,
      // 'statusBarItem.prominentHoverForeground': themes.primary,
      // 'statusBarItem.prominentHoverBackground': themes.primary,
      // 'statusBarItem.remoteBackground': themes.primary,
      // 'statusBarItem.remoteForeground': themes.primary,
      // 'statusBarItem.remoteHoverBackground': themes.primary,
      // 'statusBarItem.remoteHoverForeground': themes.primary,
      // 'statusBarItem.errorBackground': themes.primary,
      // 'statusBarItem.errorForeground': themes.error,
      // 'statusBarItem.errorHoverBackground': themes.primary,
      // 'statusBarItem.errorHoverForeground': themes.primary,
      // 'statusBarItem.warningBackground': themes.primary,
      // 'statusBarItem.warningForeground': themes.primary,
      // 'statusBarItem.warningHoverBackground': themes.primary,
      // 'statusBarItem.warningHoverForeground': themes.primary,
      // 'statusBarItem.compactHoverBackground': themes.primary,
      // 'statusBarItem.focusBorder': themes.primary,
      // 'statusBar.focusBorder': themes.primary,
      // 'statusBarItem.offlineBackground': themes.primary,
      // 'statusBarItem.offlineForeground': themes.primary,
      // 'statusBarItem.offlineHoverForeground': themes.primary,
      // 'statusBarItem.offlineHoverBackground': themes.primary,

      // Title Bar colors
      // 'titleBar.activeBackground': themes.background,
      // 'titleBar.activeForeground': themes.primary,
      // 'titleBar.inactiveBackground': themes.background,
      // 'titleBar.inactiveForeground': themes.primary,
      // 'titleBar.border': themes.primary,

      // Menu Bar colors
      // 'menubar.selectionForeground': themes.primary,
      // 'menubar.selectionBackground': themes.primary,
      // 'menubar.selectionBorder': themes.primary,
      // 'menu.foreground': themes.primary,
      // 'menu.background': themes.primary,
      // 'menu.selectionForeground': themes.primary,
      // 'menu.selectionBackground': themes.primary,
      // 'menu.selectionBorder': themes.primary,
      // 'menu.separatorBackground': themes.primary,
      // 'menu.border': themes.primary,

      // Command Center colors
      // 'commandCenter.foreground': themes.primary,
      // 'commandCenter.activeForeground': themes.primary,
      // 'commandCenter.background': themes.primary,
      // 'commandCenter.activeBackground': themes.primary,
      // 'commandCenter.border': themes.primary,
      // 'commandCenter.inactiveForeground': themes.primary,
      // 'commandCenter.inactiveBorder': themes.primary,
      // 'commandCenter.activeBorder': themes.primary,
      // 'commandCenter.debuggingBackground': themes.primary,

      // Notification colors
      'notificationCenter.border': themes.border,
      'notificationCenterHeader.foreground': themes.foreground,
      'notificationCenterHeader.background': themes.background,
      'notificationToast.border': themes.border,
      'notifications.foreground': themes.foreground,
      'notifications.background': themes.background,
      'notifications.border': themes.border,
      // 'notificationLink.foreground': themes.primary,
      // 'notificationsErrorIcon.foreground': themes.primary,
      // 'notificationsWarningIcon.foreground': themes.primary,
      // 'notificationsInfoIcon.foreground': themes.primary,

      // Banner colors
      // 'banner.background': themes.primary,
      // 'banner.foreground': themes.primary,
      // 'banner.iconForeground': themes.primary,

      // Extensions colors
      'extensionButton.prominentForeground': themes.foreground,
      // 'extensionButton.prominentBackground': themes.background,
      'extensionButton.prominentHoverBackground': themes.background,
      // 'extensionButton.background': themes.primary,
      'extensionButton.foreground': themes.foreground,
      'extensionButton.hoverBackground': themes.background,
      // 'extensionButton.separator': themes.primary,
      // 'extensionBadge.remoteBackground': themes.primary,
      // 'extensionBadge.remoteForeground': themes.primary,
      // 'extensionIcon.starForeground': themes.primary,
      // 'extensionIcon.verifiedForeground': themes.primary,
      // 'extensionIcon.preReleaseForeground': themes.primary,
      // 'extensionIcon.sponsorForeground': themes.primary,

      // Quick picker colors
      // 'pickerGroup.border': themes.primary,
      // 'pickerGroup.foreground': themes.primary,
      // 'quickInput.background': themes.primary,
      // 'quickInput.foreground': themes.primary,
      // 'quickInputList.focusBackground': themes.primary,
      // 'quickInputList.focusForeground': themes.primary,
      // 'quickInputList.focusIconForeground': themes.primary,
      // 'quickInputTitle.background': themes.primary,

      // Keybinding label colors
      'keybindingLabel.background': themes.background,
      'keybindingLabel.foreground': themes.foreground,
      'keybindingLabel.border': themes.border,
      'keybindingLabel.bottomBorder': themes.border,

      // Keyboard shortcut table colors
      'keybindingTable.headerBackground': themes.background,
      'keybindingTable.rowsBackground': themes.background,

      // Integrated Terminal colors
      'terminal.background': themes.background,
      'terminal.border': themes.border,
      'terminal.foreground': themes.foreground,
      // 'terminal.ansiBlack': themes.primary,
      // 'terminal.ansiBlue': themes.primary,
      // 'terminal.ansiBrightBlack': themes.primary,
      // 'terminal.ansiBrightBlue': themes.primary,
      // 'terminal.ansiBrightCyan': themes.primary,
      // 'terminal.ansiBrightGreen': themes.primary,
      // 'terminal.ansiBrightMagenta': themes.primary,
      // 'terminal.ansiBrightRed': themes.primary,
      // 'terminal.ansiBrightWhite': themes.primary,
      // 'terminal.ansiBrightYellow': themes.primary,
      // 'terminal.ansiCyan': themes.primary,
      // 'terminal.ansiGreen': themes.primary,
      // 'terminal.ansiMagenta': themes.primary,
      // 'terminal.ansiRed': themes.primary,
      // 'terminal.ansiWhite': themes.primary,
      // 'terminal.ansiYellow': themes.primary,
      // 'terminal.selectionBackground': themes.primary,
      // 'terminal.selectionForeground': themes.primary,
      // 'terminal.inactiveSelectionBackground': themes.primary,
      'terminal.findMatchBackground': themes.background,
      'terminal.findMatchBorder': themes.border,
      // 'terminal.findMatchHighlightBackground': themes.primary,
      'terminal.findMatchHighlightBorder': themes.border,
      // 'terminal.hoverHighlightBackground': themes.primary,
      'terminalCursor.background': themes.background,
      'terminalCursor.foreground': themes.foreground,
      // 'terminal.dropBackground': themes.primary,
      // 'terminal.tab.activeBorder': themes.primary,
      // 'terminalCommandDecoration.defaultBackground': themes.primary,
      // 'terminalCommandDecoration.successBackground': themes.primary,
      // 'terminalCommandDecoration.errorBackground': themes.primary,
      // 'terminalOverviewRuler.cursorForeground': themes.primary,
      // 'terminalOverviewRuler.findMatchForeground': themes.primary,

      // Debug colors
      'debugToolBar.background': themes.background,
      'debugToolBar.border': themes.border,
      'editor.stackFrameHighlightBackground': themes.primaryBackground,
      'editor.focusedStackFrameHighlightBackground': themes.primaryBackground,
      'editor.inlineValuesForeground': themes.foreground,
      'editor.inlineValuesBackground': themes.primaryBackground,
      // 'debugView.exceptionLabelForeground': themes.primary,
      // 'debugView.exceptionLabelBackground': themes.primary,
      'debugView.stateLabelForeground': themes.foreground,
      'debugView.stateLabelBackground': themes.primaryBackground,
      'debugView.valueChangedHighlight': themes.primaryBackground,
      'debugTokenExpression.name': themes.secondary,
      // 'debugTokenExpression.value': themes.primary,
      // 'debugTokenExpression.string': themes.primary,
      // 'debugTokenExpression.boolean': themes.primary,
      // 'debugTokenExpression.number': themes.primary,
      // 'debugTokenExpression.error': themes.primary,

      // Testing colors
      // 'testing.iconFailed': themes.primary,
      // 'testing.iconErrored': themes.primary,
      // 'testing.iconPassed': themes.primary,
      // 'testing.runAction': themes.primary,
      // 'testing.iconQueued': themes.primary,
      // 'testing.iconUnset': themes.primary,
      // 'testing.iconSkipped': themes.primary,
      // 'testing.peekBorder': themes.primary,
      // 'testing.peekHeaderBackground': themes.primary,
      // 'testing.message.error.decorationForeground': themes.primary,
      // 'testing.message.error.lineBackground': themes.primary,
      // 'testing.message.info.decorationForeground': themes.primary,
      // 'testing.message.info.lineBackground': themes.primary,

      // Welcome page colors
      // 'welcomePage.background': themes.primary,
      // 'welcomePage.progress.background': themes.primary,
      // 'welcomePage.progress.foreground': themes.primary,
      // 'welcomePage.tileBackground': themes.primary,
      // 'welcomePage.tileHoverBackground': themes.primary,
      // 'welcomePage.tileBorder': themes.primary,
      // 'walkThrough.embeddedEditorBackground': themes.primary,
      // 'walkthrough.stepTitle.foreground': themes.primary,

      // Git colors
      // 'gitDecoration.addedResourceForeground': themes.primary,
      // 'gitDecoration.modifiedResourceForeground': themes.primary,
      // 'gitDecoration.deletedResourceForeground': themes.primary,
      // 'gitDecoration.renamedResourceForeground': themes.primary,
      // 'gitDecoration.stageModifiedResourceForeground': themes.primary,
      // 'gitDecoration.stageDeletedResourceForeground': themes.primary,
      // 'gitDecoration.untrackedResourceForeground': themes.primary,
      // 'gitDecoration.ignoredResourceForeground': themes.primary,
      // 'gitDecoration.conflictingResourceForeground': themes.primary,
      // 'gitDecoration.submoduleResourceForeground': themes.primary,

      // Settings Editor colors
      // 'settings.headerForeground': themes.primary,
      // 'settings.modifiedItemIndicator': themes.primary,
      // 'settings.dropdownBackground': themes.primary,
      // 'settings.dropdownForeground': themes.primary,
      // 'settings.dropdownBorder': themes.primary,
      // 'settings.dropdownListBorder': themes.primary,
      // 'settings.checkboxBackground': themes.primary,
      // 'settings.checkboxForeground': themes.primary,
      // 'settings.checkboxBorder': themes.primary,
      // 'settings.rowHoverBackground': themes.primary,
      // 'settings.textInputBackground': themes.primary,
      // 'settings.textInputForeground': themes.primary,
      // 'settings.textInputBorder': themes.primary,
      // 'settings.numberInputBackground': themes.primary,
      // 'settings.numberInputForeground': themes.primary,
      // 'settings.numberInputBorder': themes.primary,
      // 'settings.focusedRowBackground': themes.primary,
      // 'settings.focusedRowBorder': themes.primary,
      // 'settings.headerBorder': themes.primary,
      // 'settings.sashBorder': themes.primary,
      // 'settings.settingsHeaderHoverForeground': themes.primary,

      // Breadcrumbs colors
      'breadcrumb.foreground': themes.foreground,
      // 'breadcrumb.background': themes.primary,
      'breadcrumb.focusForeground': themes.foreground,
      'breadcrumb.activeSelectionForeground': themes.foreground,
      // 'breadcrumbPicker.background': themes.primary,

      // Snippets colors
      // 'editor.snippetTabstopHighlightBackground': themes.primary,
      // 'editor.snippetTabstopHighlightBorder': themes.primary,
      // 'editor.snippetFinalTabstopHighlightBackground': themes.primary,
      // 'editor.snippetFinalTabstopHighlightBorder': themes.primary,

      // Symbol Icons colors
      // 'symbolIcon.arrayForeground': themes.primary,
      // 'symbolIcon.booleanForeground': themes.primary,
      // 'symbolIcon.classForeground': themes.primary,
      // 'symbolIcon.colorForeground': themes.primary,
      // 'symbolIcon.constantForeground': themes.primary,
      // 'symbolIcon.constructorForeground': themes.primary,
      // 'symbolIcon.enumeratorForeground': themes.primary,
      // 'symbolIcon.enumeratorMemberForeground': themes.primary,
      // 'symbolIcon.eventForeground': themes.primary,
      // 'symbolIcon.fieldForeground': themes.primary,
      // 'symbolIcon.fileForeground': themes.primary,
      // 'symbolIcon.folderForeground': themes.primary,
      // 'symbolIcon.functionForeground': themes.primary,
      // 'symbolIcon.interfaceForeground': themes.primary,
      // 'symbolIcon.keyForeground': themes.primary,
      // 'symbolIcon.keywordForeground': themes.primary,
      // 'symbolIcon.methodForeground': themes.primary,
      // 'symbolIcon.moduleForeground': themes.primary,
      // 'symbolIcon.namespaceForeground': themes.primary,
      // 'symbolIcon.nullForeground': themes.primary,
      // 'symbolIcon.numberForeground': themes.primary,
      // 'symbolIcon.objectForeground': themes.primary,
      // 'symbolIcon.operatorForeground': themes.primary,
      // 'symbolIcon.packageForeground': themes.primary,
      // 'symbolIcon.propertyForeground': themes.primary,
      // 'symbolIcon.referenceForeground': themes.primary,
      // 'symbolIcon.snippetForeground': themes.primary,
      // 'symbolIcon.stringForeground': themes.primary,
      // 'symbolIcon.structForeground': themes.primary,
      // 'symbolIcon.textForeground': themes.primary,
      // 'symbolIcon.typeParameterForeground': themes.primary,
      // 'symbolIcon.unitForeground': themes.primary,
      // 'symbolIcon.variableForeground': themes.primary,

      // Debug Icons colors
      // 'debugIcon.breakpointForeground': themes.primary,
      // 'debugIcon.breakpointDisabledForeground': themes.primary,
      // 'debugIcon.breakpointUnverifiedForeground': themes.primary,
      // 'debugIcon.breakpointCurrentStackframeForeground': themes.primary,
      // 'debugIcon.breakpointStackframeForeground': themes.primary,
      // 'debugIcon.startForeground': themes.primary,
      // 'debugIcon.pauseForeground': themes.primary,
      // 'debugIcon.stopForeground': themes.primary,
      // 'debugIcon.disconnectForeground': themes.primary,
      // 'debugIcon.restartForeground': themes.primary,
      // 'debugIcon.stepOverForeground': themes.primary,
      // 'debugIcon.stepIntoForeground': themes.primary,
      // 'debugIcon.stepOutForeground': themes.primary,
      // 'debugIcon.continueForeground': themes.primary,
      // 'debugIcon.stepBackForeground': themes.primary,
      // 'debugConsole.infoForeground': themes.primary,
      // 'debugConsole.warningForeground': themes.primary,
      // 'debugConsole.errorForeground': themes.primary,
      // 'debugConsole.sourceForeground': themes.primary,
      // 'debugConsoleInputIcon.foreground': themes.primary,

      // Notebook colors
      // 'notebook.editorBackground':themes.primary,
      // 'notebook.cellBorderColor':themes.primary,
      // 'notebook.cellHoverBackground':themes.primary,
      // 'notebook.cellInsertionIndicator':themes.primary,
      // 'notebook.cellStatusBarItemHoverBackground':themes.primary,
      // 'notebook.cellToolbarSeparator':themes.primary,
      // 'notebook.cellEditorBackground':themes.primary,
      // 'notebook.focusedCellBackground':themes.primary,
      // 'notebook.focusedCellBorder':themes.primary,
      // 'notebook.focusedEditorBorder':themes.primary,
      // 'notebook.inactiveFocusedCellBorder':themes.primary,
      // 'notebook.inactiveSelectedCellBorder':themes.primary,
      // 'notebook.outputContainerBackgroundColor':themes.primary,
      // 'notebook.outputContainerBorderColor':themes.primary,
      // 'notebook.selectedCellBackground':themes.primary,
      // 'notebook.selectedCellBorder':themes.primary,
      // 'notebook.symbolHighlightBackground':themes.primary,
      // 'notebookScrollbarSlider.activeBackground':themes.primary,
      // 'notebookScrollbarSlider.background':themes.primary,
      // 'notebookScrollbarSlider.hoverBackground':themes.primary,
      // 'notebookStatusErrorIcon.foreground':themes.primary,
      // 'notebookStatusRunningIcon.foreground':themes.primary,
      // 'notebookStatusSuccessIcon.foreground':themes.primary,
      // 'notebookEditorOverviewRuler.runningCellForeground':themes.primary,

      // Chart colors
      // 'charts.foreground': themes.primary,
      // 'charts.lines': themes.primary,
      // 'charts.red': themes.primary,
      // 'charts.blue': themes.primary,
      // 'charts.yellow': themes.primary,
      // 'charts.orange': themes.primary,
      // 'charts.green': themes.primary,
      // 'charts.purple': themes.primary,

      // Ports Colors
      // 'ports.iconRunningProcessForeground':themes.primary,

      // Comments View colors
      // 'commentsView.resolvedIcon': themes.primary,
      // 'commentsView.unresolvedIcon': themes.primary,

      // Action Bar colors
      'actionBar.toggledBackground': themes.primaryBackground

      // Simple Find Widget
      // 'simpleFindWidget.sashBorder':themes.primary,
    },
    tokenColors: [
      // comment
      {
        scope: ['comment', 'comment.block.documentation'],
        settings: themes.comment
      },
      // string
      {
        scope: ['string'],
        settings: themes.string
      },
      // regex
      {
        scope: ['regex'],
        settings: themes.regex
      },
      // number
      {
        scope: ['number', 'constant.numeric.decimal'],
        settings: themes.number
      },
      // undefined
      {
        scope: ['constant.language.undefined'],
        settings: themes.undefined
      },
      // boolean
      {
        scope: [
          'boolean',
          'constant.language.boolean',
          'constant.language.json'
        ],
        settings: themes.boolean
      },
      // keyword
      {
        scope: ['keyword'],
        settings: themes.keyword
      },
      // function
      {
        scope: ['function', 'entity.name.function'],
        settings: themes.function
      },
      // html
      {
        scope: ['entity.other.attribute-name.html'],
        settings: themes.bold
      },
      // json
      {
        scope: ['support.type.property-name.json'],
        settings: themes.default
      },
      // markdown
      {
        scope: [
          'punctuation.definition.list.begin.markdown',
          'punctuation.definition.quote.begin.markdown',
          'punctuation.definition.heading.markdown',
          'punctuation.definition.bold.markdown',
          'punctuation.definition.italic.markdown',
          'punctuation.definition.raw.markdown',
          'punctuation.definition.markdown',
          'fenced_code.block.language.markdown',
          'meta.separator.markdown',
          'punctuation.definition.link.title.begin.markdown',
          'punctuation.definition.link.title.end.markdown',
          'punctuation.definition.metadata.markdown',
          'punctuation.definition.link.markdown'
        ],
        settings: themes.gray
      },
      {
        scope: [
          'string.other.link.title.markdown',
          'string.other.link.description.title.markdown',
          'string.other.link.description.markdown'
        ],
        settings: themes.default
      },
      // yaml
      {
        scope: ['entity.name.tag.yaml'],
        settings: themes.default
      },
      // js
      {
        scope: ['storage.type.js', 'storage.modifier.js'],
        settings: themes.keyword
      },
      // ts
      {
        scope: [
          'storage.type.ts',
          'storage.type.interface.ts',
          'storage.type.function.ts',
          'support.type.primitive.ts',
          'support.type.builtin.ts',
          'storage.modifier.async.ts'
        ],
        settings: themes.keyword
      },
      // vue
      {
        scope: [
          'keyword.control.loop.vue',
          'punctuation.attribute-shorthand.bind.html.vue',
          'punctuation.attribute-shorthand.event.html.vue'
        ],
        settings: themes.bold
      }
    ]
  }
  return theme
}
